;; キーバインド
;(global-set-key [f3]  'ibuffer)
;(global-set-key [f5]  'folding-mode)
;(global-set-key [f7]  'enlarge-window-horizontally)
;(global-set-key [f8]  'enlarge-window)
(global-set-key [delete] 'delete-backward-char)
(global-set-key [kp-delete] 'delete-backward-char)
(global-set-key "\C-h" 'delete-backward-char)
(global-set-key "\M-p" 'scroll-down)
(global-set-key "\M-n" 'scroll-up)
(global-set-key "\C-x\C-n" 'goto-line)
(global-set-key "\C-_" 'undo)
(global-set-key "\C-u" 'undo)
(global-set-key "\C-x\C-u" 'universal-argument)
(define-key minibuffer-local-completion-map "\C-w" 'backward-kill-word)  ;; ミニバッファで単語削除
(global-set-key "\C-x\C-r" 'point-to-register)
(global-set-key "\C-x\C-j" 'jump-to-register)
(global-unset-key "\C-z")

;; tab-bar-mode
(global-set-key "\C-z\C-c" 'tab-bar-new-tab)
(global-set-key "\C-zc" 'tab-bar-new-tab)
(global-set-key "\C-z\C-k" 'tab-bar-close-tab)
(global-set-key "\C-zk" 'tab-bar-close-tab)
(global-set-key "\C-z\C-p" 'tab-previous)
(global-set-key "\C-z\C-n" 'tab-next)
