(when (locate-library "elscreen")
  (setq elscreen-prefix-key "\C-z")
  (require 'elscreen))
(global-set-key "\M-}" 'elscreen-next)
(global-set-key "\M-{" 'elscreen-previous)
(define-key elscreen-map "\C-k" 'elscreen-kill-screen-and-buffers)
